module.exports = {
  retrievedAt: "01 Jan 08:39:33",
  charts: {
    NZBC: "http://www.aip.net.nz/pdf/NZBC.pdf",
    NZAW: "http://www.aip.net.nz/pdf/NZAW.pdf",
    NZJL: "http://www.aip.net.nz/pdf/NZJL.pdf",
    NZAL: "http://www.aip.net.nz/pdf/NZAL.pdf",
    NZBA: "http://www.aip.net.nz/pdf/NZBA.pdf",
    NZBW: "http://www.aip.net.nz/pdf/NZBW.pdf",
    NZCG: "http://www.aip.net.nz/pdf/NZCG.pdf",
    NZCB: "http://www.aip.net.nz/pdf/NZCB.pdf",
    NZJC: "http://www.aip.net.nz/pdf/NZJC.pdf",
    NZJJ: "http://www.aip.net.nz/pdf/NZJJ.pdf",
    NZCL: "http://www.aip.net.nz/pdf/NZCL.pdf",
    NZCW: "http://www.aip.net.nz/pdf/NZCW.pdf",
    NZCS: "http://www.aip.net.nz/pdf/NZCS.pdf",
    NZDV: "http://www.aip.net.nz/pdf/NZDV.pdf",
    NZDA: "http://www.aip.net.nz/pdf/NZDA.pdf",
    NZDC: "http://www.aip.net.nz/pdf/NZDC.pdf",
    NZEV: "http://www.aip.net.nz/pdf/NZEV.pdf",
    NZFG: "http://www.aip.net.nz/pdf/NZFG.pdf",
    NZFE: "http://www.aip.net.nz/pdf/NZFE.pdf",
    NZFL: "http://www.aip.net.nz/pdf/NZFL.pdf",
    NZFT: "http://www.aip.net.nz/pdf/NZFT.pdf",
    NZFF: "http://www.aip.net.nz/pdf/NZFF.pdf",
    NZFH: "http://www.aip.net.nz/pdf/NZFH.pdf",
    NZFO: "http://www.aip.net.nz/pdf/NZFO.pdf",
    NZFP: "http://www.aip.net.nz/pdf/NZFP.pdf",
    NZFJ: "http://www.aip.net.nz/pdf/NZFJ.pdf",
    NZGA: "http://www.aip.net.nz/pdf/NZGA.pdf",
    NZJG: "http://www.aip.net.nz/pdf/NZJG.pdf",
    NZGY: "http://www.aip.net.nz/pdf/NZGY.pdf",
    NZGC: "http://www.aip.net.nz/pdf/NZGC.pdf",
    NZHT: "http://www.aip.net.nz/pdf/NZHT.pdf",
    NZJH: "http://www.aip.net.nz/pdf/NZJH.pdf",
    NZHB: "http://www.aip.net.nz/pdf/NZHB.pdf",
    NZHF: "http://www.aip.net.nz/pdf/NZHF.pdf",
    NZKO: "http://www.aip.net.nz/pdf/NZKO.pdf",
    NZKJ: "http://www.aip.net.nz/pdf/NZKJ.pdf",
    NZKF: "http://www.aip.net.nz/pdf/NZKF.pdf",
    NZKM: "http://www.aip.net.nz/pdf/NZKM.pdf",
    NZWE: "http://www.aip.net.nz/pdf/NZWE.pdf",
    NZKH: "http://www.aip.net.nz/pdf/NZKH.pdf",
    NZKP: "http://www.aip.net.nz/pdf/NZKP.pdf",
    NZKY: "http://www.aip.net.nz/pdf/NZKY.pdf",
    NZKU: "http://www.aip.net.nz/pdf/NZKU.pdf",
    NZHP: "http://www.aip.net.nz/pdf/NZHP.pdf",
    NZLE: "http://www.aip.net.nz/pdf/NZLE.pdf",
    NZLA1: "http://www.aip.net.nz/pdf/NZLA1.pdf",
    NZMX: "http://www.aip.net.nz/pdf/NZMX.pdf",
    NZMW: "http://www.aip.net.nz/pdf/NZMW.pdf",
    NZOG: "http://www.aip.net.nz/pdf/NZOG.pdf",
    NZVL: "http://www.aip.net.nz/pdf/NZVL.pdf",
    NZMG: "http://www.aip.net.nz/pdf/NZMG.pdf",
    NZSO: "http://www.aip.net.nz/pdf/NZSO.pdf",
    NZMJ: "http://www.aip.net.nz/pdf/NZMJ.pdf",
    NZUB: "http://www.aip.net.nz/pdf/NZUB.pdf",
    NZME: "http://www.aip.net.nz/pdf/NZME.pdf",
    NZML: "http://www.aip.net.nz/pdf/NZML.pdf",
    NZKD: "http://www.aip.net.nz/pdf/NZKD.pdf",
    NZMK: "http://www.aip.net.nz/pdf/NZMK.pdf",
    NZMR: "http://www.aip.net.nz/pdf/NZMR.pdf",
    NZUR: "http://www.aip.net.nz/pdf/NZUR.pdf",
    NZNH: "http://www.aip.net.nz/pdf/NZNH.pdf",
    NZNF: "http://www.aip.net.nz/pdf/NZNF.pdf",
    NZJN: "http://www.aip.net.nz/pdf/NZJN.pdf",
    NZOB: "http://www.aip.net.nz/pdf/NZOB.pdf",
    NZOX: "http://www.aip.net.nz/pdf/NZOX.pdf",
    NZOF: "http://www.aip.net.nz/pdf/NZOF.pdf",
    NZOA: "http://www.aip.net.nz/pdf/NZOA.pdf",
    NZOP: "http://www.aip.net.nz/pdf/NZOP.pdf",
    NZOT: "http://www.aip.net.nz/pdf/NZOT.pdf",
    NZPA: "http://www.aip.net.nz/pdf/NZPA.pdf",
    NZJM: "http://www.aip.net.nz/pdf/NZJM.pdf",
    NZPW: "http://www.aip.net.nz/pdf/NZPW.pdf",
    NZPO: "http://www.aip.net.nz/pdf/NZPO.pdf",
    NZPH: "http://www.aip.net.nz/pdf/NZPH.pdf",
    NZUK: "http://www.aip.net.nz/pdf/NZUK.pdf",
    NZPU: "http://www.aip.net.nz/pdf/NZPU.pdf",
    NZRA: "http://www.aip.net.nz/pdf/NZRA.pdf",
    NZRT: "http://www.aip.net.nz/pdf/NZRT.pdf",
    NZRK: "http://www.aip.net.nz/pdf/NZRK.pdf",
    NZRI: "http://www.aip.net.nz/pdf/NZRI.pdf",
    NZJW: "http://www.aip.net.nz/pdf/NZJW.pdf",
    NZJO: "http://www.aip.net.nz/pdf/NZJO.pdf",
    NZLF: "http://www.aip.net.nz/pdf/NZLF.pdf",
    NZRL: "http://www.aip.net.nz/pdf/NZRL.pdf",
    NZRX: "http://www.aip.net.nz/pdf/NZRX.pdf",
    NZRW: "http://www.aip.net.nz/pdf/NZRW.pdf",
    NZSH: "http://www.aip.net.nz/pdf/NZSH.pdf",
    NZSF: "http://www.aip.net.nz/pdf/NZSF.pdf",
    NZSD: "http://www.aip.net.nz/pdf/NZSD.pdf",
    NZAH: "http://www.aip.net.nz/pdf/NZAH.pdf",
    NZVR: "http://www.aip.net.nz/pdf/NZVR.pdf",
    NZJQ: "http://www.aip.net.nz/pdf/NZJQ.pdf",
    NZTM: "http://www.aip.net.nz/pdf/NZTM.pdf",
    NZJZ: "http://www.aip.net.nz/pdf/NZJZ.pdf",
    NZLT: "http://www.aip.net.nz/pdf/NZLT.pdf",
    NZJA: "http://www.aip.net.nz/pdf/NZJA.pdf",
    NZTE: "http://www.aip.net.nz/pdf/NZTE.pdf",
    NZJP: "http://www.aip.net.nz/pdf/NZJP.pdf",
    NZTL: "http://www.aip.net.nz/pdf/NZTL.pdf",
    NZTP: "http://www.aip.net.nz/pdf/NZTP.pdf",
    NZJD: "http://www.aip.net.nz/pdf/NZJD.pdf",
    NZUI: "http://www.aip.net.nz/pdf/NZUI.pdf",
    NZTN: "http://www.aip.net.nz/pdf/NZTN.pdf",
    NZWV: "http://www.aip.net.nz/pdf/NZWV.pdf",
    NZHH: "http://www.aip.net.nz/pdf/NZHH.pdf",
    NZWM: "http://www.aip.net.nz/pdf/NZWM.pdf",
    NZYP: "http://www.aip.net.nz/pdf/NZYP.pdf",
    NZMH: "http://www.aip.net.nz/pdf/NZMH.pdf",
    NZJB: "http://www.aip.net.nz/pdf/NZJB.pdf",
    NZJY: "http://www.aip.net.nz/pdf/NZJY.pdf",
    NZWH: "http://www.aip.net.nz/pdf/NZWH.pdf",
    NZWL: "http://www.aip.net.nz/pdf/NZWL.pdf",
    NZJF: "http://www.aip.net.nz/pdf/NZJF.pdf",
    NZJU: "http://www.aip.net.nz/pdf/NZJU.pdf",
    NZJR: "http://www.aip.net.nz/pdf/NZJR.pdf",
    NZES: "http://www.aip.net.nz/pdf/NZES.pdf",
    NZWY: "http://www.aip.net.nz/pdf/NZWY.pdf",
    NZLX: [
      "http://www.aip.net.nz/pdf/NZLX_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZLX_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZLX_62.1.pdf"
    ],
    NZAR: [
      "http://www.aip.net.nz/pdf/NZAR_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZAR_31.3_31.4.pdf",
      "http://www.aip.net.nz/pdf/NZAR_31.5.pdf",
      "http://www.aip.net.nz/pdf/NZAR_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZAR_35.3_35.4.pdf",
      "http://www.aip.net.nz/pdf/NZAR_35.5_35.6.pdf",
      "http://www.aip.net.nz/pdf/NZAR_35.7_35.8.pdf",
      "http://www.aip.net.nz/pdf/NZAR_35.9_35.10.pdf",
      "http://www.aip.net.nz/pdf/NZAR_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZAR_45.2_45.3.pdf",
      "http://www.aip.net.nz/pdf/NZAR_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZAR_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZAR_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZAR_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZAR_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZAR_62.5.pdf"
    ],
    NZAS: ["http://www.aip.net.nz/pdf/NZAS_51.1_52.1.pdf"],
    NZAA: [
      "http://www.aip.net.nz/pdf/NZAA_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.3_31.4.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.5_31.6.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.7_31.8.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.9.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.10_31.11.pdf",
      "http://www.aip.net.nz/pdf/NZAA_31.12_31.13.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.5_33.6.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.7_33.8.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.9_33.10.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.11_33.12.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.13_33.14.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.15_33.16.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.17_33.18.pdf",
      "http://www.aip.net.nz/pdf/NZAA_33.19_33.20.pdf",
      "http://www.aip.net.nz/pdf/NZAA_34.1_34.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_41.1_41.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_41.3.pdf",
      "http://www.aip.net.nz/pdf/NZAA_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZAA_45.5_45.6.pdf",
      "http://www.aip.net.nz/pdf/NZAA_45.7_45.8.pdf",
      "http://www.aip.net.nz/pdf/NZAA_45.9.pdf",
      "http://www.aip.net.nz/pdf/NZAA_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZAA_52.2_52.3.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.2_53.3.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.4_53.5.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.6_53.7.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.8_53.9.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.10.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.11_53.12.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.13_53.14.pdf",
      "http://www.aip.net.nz/pdf/NZAA_53.15_53.16.pdf",
      "http://www.aip.net.nz/pdf/NZAA_54.1_54.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.9_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.11_62.12.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.13_62.14.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.15_62.16.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.17_62.18.pdf",
      "http://www.aip.net.nz/pdf/NZAA_62.19_62.20.pdf",
      "http://www.aip.net.nz/pdf/NZAA_64.1.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.1Y_70.2Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.3Y_70.4Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.5Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.10Y_70.11Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.14Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.21Y_70.22Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.23Y_70.24Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.25Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.30Y_70.31Y.pdf",
      "http://www.aip.net.nz/pdf/NZAA_70.34Y.pdf"
    ],
    NZJI: [
      "http://www.aip.net.nz/pdf/NZJI_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZJI_51.1_52.1.pdf"
    ],
    NZCI: [
      "http://www.aip.net.nz/pdf/NZCI_44.1.pdf",
      "http://www.aip.net.nz/pdf/NZCI_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZCI_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZCI_62.1.pdf"
    ],
    NZCH: [
      "http://www.aip.net.nz/pdf/NZCH_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_31.3.pdf",
      "http://www.aip.net.nz/pdf/NZCH_31.4Y_31.5Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_31.6Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.5_33.6.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.7_33.8.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.9_33.10.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.11_33.12.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.13_33.14.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.15_33.16.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.17_33.18.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.19_33.20.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.21_33.22.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.23_33.24.pdf",
      "http://www.aip.net.nz/pdf/NZCH_33.25_33.26.pdf",
      "http://www.aip.net.nz/pdf/NZCH_34.1_34.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_35.3_35.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_41.1_41.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.5_45.6.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.7_45.8.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.9.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.10_45.11.pdf",
      "http://www.aip.net.nz/pdf/NZCH_45.12_45.13.pdf",
      "http://www.aip.net.nz/pdf/NZCH_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZCH_52.2_52.3.pdf",
      "http://www.aip.net.nz/pdf/NZCH_52.4_52.5.pdf",
      "http://www.aip.net.nz/pdf/NZCH_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_53.3_53.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_53.5_53.6.pdf",
      "http://www.aip.net.nz/pdf/NZCH_53.7_53.8.pdf",
      "http://www.aip.net.nz/pdf/NZCH_54.1_54.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_61.1_61.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.9_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZCH_62.11_62.12.pdf",
      "http://www.aip.net.nz/pdf/NZCH_64.1_64.2.pdf",
      "http://www.aip.net.nz/pdf/NZCH_64.3_64.4.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.1Y_70.2Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.3Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.10Y_70.11Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.12Y_70.14Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.21Y_70.22Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.23Y_70.24Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.25Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.30Y_70.31Y.pdf",
      "http://www.aip.net.nz/pdf/NZCH_70.32Y_70.34Y.pdf"
    ],
    NZCX: [
      "http://www.aip.net.nz/pdf/NZCX_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZCX_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZCX_62.1.pdf"
    ],
    NZJE: [
      "http://www.aip.net.nz/pdf/NZJE_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZJE_51.1_52.1.pdf"
    ],
    NZDN: [
      "http://www.aip.net.nz/pdf/NZDN_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZDN_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZDN_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZDN_33.4_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZDN_33.6_33.7.pdf",
      "http://www.aip.net.nz/pdf/NZDN_35.1.pdf",
      "http://www.aip.net.nz/pdf/NZDN_41.1_41.2.pdf",
      "http://www.aip.net.nz/pdf/NZDN_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZDN_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZDN_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZDN_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZDN_52.2_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZDN_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZDN_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZDN_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZDN_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZDN_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZDN_64.1.pdf"
    ],
    NZDH: [
      "http://www.aip.net.nz/pdf/NZDH_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZDH_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZDH_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZDH_62.1.pdf"
    ],
    NZDU: [
      "http://www.aip.net.nz/pdf/NZDU_33.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZDU_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZDU_62.1.pdf"
    ],
    NZFI: [
      "http://www.aip.net.nz/pdf/NZFI_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZFI_52.1.pdf"
    ],
    NZGS: [
      "http://www.aip.net.nz/pdf/NZGS_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZGS_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_43.1.pdf",
      "http://www.aip.net.nz/pdf/NZGS_43.2_43.3.pdf",
      "http://www.aip.net.nz/pdf/NZGS_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZGS_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZGS_62.3_62.4.pdf"
    ],
    NZGH: [
      "http://www.aip.net.nz/pdf/NZGH_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZGH_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZGH_52.1_53.1.pdf"
    ],
    NZGT: [
      "http://www.aip.net.nz/pdf/NZGT_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZGT_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZGT_62.1.pdf"
    ],
    NZGB: [
      "http://www.aip.net.nz/pdf/NZGB_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZGB_45.2_45.3.pdf",
      "http://www.aip.net.nz/pdf/NZGB_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZGB_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZGB_62.1_62.2.pdf"
    ],
    NZGR: [
      "http://www.aip.net.nz/pdf/NZGR_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZGR_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZGR_62.1.pdf"
    ],
    NZGM: [
      "http://www.aip.net.nz/pdf/NZGM_33.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZGM_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZGM_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZGM_62.2_62.3.pdf"
    ],
    NZHN: [
      "http://www.aip.net.nz/pdf/NZHN_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZHN_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZHN_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZHN_33.6_33.7.pdf",
      "http://www.aip.net.nz/pdf/NZHN_33.8_33.9.pdf",
      "http://www.aip.net.nz/pdf/NZHN_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_35.3.pdf",
      "http://www.aip.net.nz/pdf/NZHN_35.4_35.5.pdf",
      "http://www.aip.net.nz/pdf/NZHN_35.6.pdf",
      "http://www.aip.net.nz/pdf/NZHN_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_43.3.pdf",
      "http://www.aip.net.nz/pdf/NZHN_43.4_43.5.pdf",
      "http://www.aip.net.nz/pdf/NZHN_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZHN_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZHN_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.9_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.11_62.12.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.13_62.14.pdf",
      "http://www.aip.net.nz/pdf/NZHN_62.15.pdf"
    ],
    NZHS: [
      "http://www.aip.net.nz/pdf/NZHS_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZHS_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZHS_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZHS_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZHS_62.3.pdf"
    ],
    NZHA: [
      "http://www.aip.net.nz/pdf/NZHA_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZHA_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZHA_51.1_52.1.pdf"
    ],
    NZHK: [
      "http://www.aip.net.nz/pdf/NZHK_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZHK_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZHK_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZHK_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZHK_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZHK_62.1.pdf"
    ],
    NZNV: [
      "http://www.aip.net.nz/pdf/NZNV_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZNV_31.2_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZNV_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZNV_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZNV_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZNV_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZNV_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZNV_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZNV_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZNV_62.1_62.2.pdf"
    ],
    NZKI: [
      "http://www.aip.net.nz/pdf/NZKI_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZKI_31.2_44.1.pdf",
      "http://www.aip.net.nz/pdf/NZKI_51.1_52.1.pdf"
    ],
    NZKT: [
      "http://www.aip.net.nz/pdf/NZKT_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZKT_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZKT_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZKT_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZKT_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZKT_62.1_62.2.pdf"
    ],
    NZJK: [
      "http://www.aip.net.nz/pdf/NZJK_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZJK_51.1_52.1.pdf"
    ],
    NZKK: [
      "http://www.aip.net.nz/pdf/NZKK_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZKK_44.3_44.4.pdf",
      "http://www.aip.net.nz/pdf/NZKK_44.5_44.6.pdf",
      "http://www.aip.net.nz/pdf/NZKK_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZKK_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZKK_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZKK_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZKK_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZKK_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZKK_62.3.pdf"
    ],
    NZMS: [
      "http://www.aip.net.nz/pdf/NZMS_31.1_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZMS_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZMS_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZMS_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZMS_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZMS_62.3_62.4.pdf"
    ],
    NZMA: [
      "http://www.aip.net.nz/pdf/NZMA_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZMA_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZMA_55.1.pdf"
    ],
    NZUA: [
      "http://www.aip.net.nz/pdf/NZUA_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZUA_45.1.pdf"
    ],
    NZMB: [
      "http://www.aip.net.nz/pdf/NZMB_33.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZMB_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZMB_62.1.pdf"
    ],
    NZMF: [
      "http://www.aip.net.nz/pdf/NZMF_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZMF_31.3.pdf",
      "http://www.aip.net.nz/pdf/NZMF_31.4.pdf",
      "http://www.aip.net.nz/pdf/NZMF_51.1_52.1.pdf"
    ],
    MC_5: [
      "http://www.aip.net.nz/pdf/MC_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/MC_61.1.pdf"
    ],
    NZNR: [
      "http://www.aip.net.nz/pdf/NZNR_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZNR_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZNR_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZNR_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZNR_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZNR_62.3_62.4.pdf"
    ],
    NZNS: [
      "http://www.aip.net.nz/pdf/NZNS_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZNS_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZNS_33.4_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZNS_35.1.pdf",
      "http://www.aip.net.nz/pdf/NZNS_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_45.3.pdf",
      "http://www.aip.net.nz/pdf/NZNS_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.5.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.6_62.7.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.8_62.9.pdf",
      "http://www.aip.net.nz/pdf/NZNS_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZNS_64.1.pdf"
    ],
    NZNP: [
      "http://www.aip.net.nz/pdf/NZNP_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZNP_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZNP_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZNP_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_35.3.pdf",
      "http://www.aip.net.nz/pdf/NZNP_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZNP_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZNP_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.5.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.6_62.7.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.8_62.9.pdf",
      "http://www.aip.net.nz/pdf/NZNP_62.10.pdf"
    ],
    NZNE: [
      "http://www.aip.net.nz/pdf/NZNE_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZNE_31.2_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZNE_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZNE_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZNE_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZNE_61.1_62.1.pdf"
    ],
    NZOU: [
      "http://www.aip.net.nz/pdf/NZOU_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZOU_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZOU_62.1.pdf"
    ],
    NZOR: [
      "http://www.aip.net.nz/pdf/NZOR_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZOR_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZOR_62.1.pdf"
    ],
    NZOH: [
      "http://www.aip.net.nz/pdf/NZOH_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZOH_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_41.1_41.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZOH_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZOH_45.2_45.3.pdf",
      "http://www.aip.net.nz/pdf/NZOH_45.4_45.5.pdf",
      "http://www.aip.net.nz/pdf/NZOH_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_53.3_53.4.pdf",
      "http://www.aip.net.nz/pdf/NZOH_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZOH_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZOH_62.3_62.4.pdf"
    ],
    NZOM: [
      "http://www.aip.net.nz/pdf/NZOM_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZOM_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZOM_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZOM_53.1.pdf"
    ],
    NZPM: [
      "http://www.aip.net.nz/pdf/NZPM_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZPM_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZPM_33.4_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZPM_33.6_33.7.pdf",
      "http://www.aip.net.nz/pdf/NZPM_33.8_33.9.pdf",
      "http://www.aip.net.nz/pdf/NZPM_34.1_34.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_35.3.pdf",
      "http://www.aip.net.nz/pdf/NZPM_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_43.3.pdf",
      "http://www.aip.net.nz/pdf/NZPM_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_45.3.pdf",
      "http://www.aip.net.nz/pdf/NZPM_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.9_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.11.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.12_62.13.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.14_62.15.pdf",
      "http://www.aip.net.nz/pdf/NZPM_62.16.pdf",
      "http://www.aip.net.nz/pdf/NZPM_64.1.pdf"
    ],
    NZPI: [
      "http://www.aip.net.nz/pdf/NZPI_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZPI_52.1.pdf"
    ],
    NZPP: [
      "http://www.aip.net.nz/pdf/NZPP_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_31.3_31.4.pdf",
      "http://www.aip.net.nz/pdf/NZPP_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_35.3_35.4.pdf",
      "http://www.aip.net.nz/pdf/NZPP_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZPP_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZPP_62.3_62.4.pdf"
    ],
    NZUN: [
      "http://www.aip.net.nz/pdf/NZUN_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZUN_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZUN_52.1.pdf"
    ],
    NZPN: [
      "http://www.aip.net.nz/pdf/NZPN_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZPN_62.1.pdf"
    ],
    NZPK: [
      "http://www.aip.net.nz/pdf/NZPK_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZPK_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZPK_62.1.pdf"
    ],
    NZQW: [
      "http://www.aip.net.nz/pdf/NZQW_35.1.pdf",
      "http://www.aip.net.nz/pdf/NZQW_51.1_52.1.pdf"
    ],
    NZQN: [
      "http://www.aip.net.nz/pdf/NZQN_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZQN_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZQN_33.5_33.6.pdf",
      "http://www.aip.net.nz/pdf/NZQN_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_35.3_35.4.pdf",
      "http://www.aip.net.nz/pdf/NZQN_35.5_35.6.pdf",
      "http://www.aip.net.nz/pdf/NZQN_35.7.pdf",
      "http://www.aip.net.nz/pdf/NZQN_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZQN_45.5.pdf",
      "http://www.aip.net.nz/pdf/NZQN_45.6_45.7.pdf",
      "http://www.aip.net.nz/pdf/NZQN_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_51.3.pdf",
      "http://www.aip.net.nz/pdf/NZQN_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.5_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.9_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.11.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.12_62.13.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.14_62.15.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.16_62.17.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.18.pdf",
      "http://www.aip.net.nz/pdf/NZQN_62.19_62.20.pdf",
      "http://www.aip.net.nz/pdf/NZQN_64.1_64.2.pdf",
      "http://www.aip.net.nz/pdf/NZQN_64.3.pdf"
    ],
    NZRO: [
      "http://www.aip.net.nz/pdf/NZRO_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZRO_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZRO_33.4_33.5.pdf",
      "http://www.aip.net.nz/pdf/NZRO_33.6.pdf",
      "http://www.aip.net.nz/pdf/NZRO_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZRO_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZRO_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZRO_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZRO_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZRO_62.5_62.6.pdf"
    ],
    NZRC: ["http://www.aip.net.nz/pdf/NZRC_51.1_52.1.pdf"],
    NZJS: [
      "http://www.aip.net.nz/pdf/NZJS_33.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZJS_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZJS_62.1.pdf"
    ],
    NZSL: [
      "http://www.aip.net.nz/pdf/NZSL_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZSL_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZSL_62.1.pdf"
    ],
    NZTI: [
      "http://www.aip.net.nz/pdf/NZTI_35.1.pdf",
      "http://www.aip.net.nz/pdf/NZTI_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZTI_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZTI_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZTI_64.1.pdf"
    ],
    NZTK: [
      "http://www.aip.net.nz/pdf/NZTK_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZTK_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZTK_62.1.pdf"
    ],
    NZJT: [
      "http://www.aip.net.nz/pdf/NZJT_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZJT_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZJT_62.1.pdf"
    ],
    NZAP: [
      "http://www.aip.net.nz/pdf/NZAP_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZAP_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_44.3_44.4.pdf",
      "http://www.aip.net.nz/pdf/NZAP_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZAP_61.1_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZAP_62.2_62.3.pdf",
      "http://www.aip.net.nz/pdf/NZAP_62.4_62.5.pdf",
      "http://www.aip.net.nz/pdf/NZAP_62.6_62.7.pdf"
    ],
    NZTG: [
      "http://www.aip.net.nz/pdf/NZTG_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZTG_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZTG_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZTG_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZTG_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZTG_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZTG_64.1_64.2.pdf"
    ],
    NZMO: [
      "http://www.aip.net.nz/pdf/NZMO_31.1_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZMO_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZMO_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZMO_62.1.pdf"
    ],
    NZTT: ["http://www.aip.net.nz/pdf/NZTT_51.1_52.1.pdf"],
    NZTQ: [
      "http://www.aip.net.nz/pdf/NZTQ_33.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZTQ_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZTQ_62.1.pdf"
    ],
    NZTH: [
      "http://www.aip.net.nz/pdf/NZTH_31.1_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZTH_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZTH_62.1.pdf"
    ],
    NZTU: [
      "http://www.aip.net.nz/pdf/NZTU_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZTU_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZTU_44.1.pdf",
      "http://www.aip.net.nz/pdf/NZTU_44.2_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZTU_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZTU_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZTU_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZTU_61.1_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZTU_62.2_62.3.pdf"
    ],
    NZTO: [
      "http://www.aip.net.nz/pdf/NZTO_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZTO_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZTO_51.1_52.1.pdf"
    ],
    NZJX: [
      "http://www.aip.net.nz/pdf/NZJX_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZJX_62.1.pdf"
    ],
    NZKE: [
      "http://www.aip.net.nz/pdf/NZKE_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZKE_51.1_52.1.pdf"
    ],
    NZWO: [
      "http://www.aip.net.nz/pdf/NZWO_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZWO_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZWO_62.1.pdf"
    ],
    NZWF: [
      "http://www.aip.net.nz/pdf/NZWF_31.1_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZWF_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZWF_35.3_35.4.pdf",
      "http://www.aip.net.nz/pdf/NZWF_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZWF_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWF_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZWF_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZWF_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZWF_62.2_62.3.pdf"
    ],
    NZWN: [
      "http://www.aip.net.nz/pdf/NZWN_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_31.3_31.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_31.5_31.6.pdf",
      "http://www.aip.net.nz/pdf/NZWN_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_33.5_33.6.pdf",
      "http://www.aip.net.nz/pdf/NZWN_33.7.pdf",
      "http://www.aip.net.nz/pdf/NZWN_35.1_35.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_41.1_41.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_45.5.pdf",
      "http://www.aip.net.nz/pdf/NZWN_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_53.3_53.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_53.5_53.6.pdf",
      "http://www.aip.net.nz/pdf/NZWN_54.1_54.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_54.3_54.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_54.5.pdf",
      "http://www.aip.net.nz/pdf/NZWN_61.1_61.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.3_62.4.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.5.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.6_62.7.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.8_62.9.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.10.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.11_62.12.pdf",
      "http://www.aip.net.nz/pdf/NZWN_62.13.pdf",
      "http://www.aip.net.nz/pdf/NZWN_64.1_64.2.pdf"
    ],
    NZWJ: [
      "http://www.aip.net.nz/pdf/NZWJ_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWJ_62.1.pdf"
    ],
    NZWS: [
      "http://www.aip.net.nz/pdf/NZWS_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZWS_33.2_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZWS_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZWS_44.3.pdf",
      "http://www.aip.net.nz/pdf/NZWS_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWS_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZWS_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZWS_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZWS_62.1.pdf"
    ],
    NZWK: [
      "http://www.aip.net.nz/pdf/NZWK_31.1_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZWK_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZWK_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWK_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWK_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZWK_61.1_62.1.pdf"
    ],
    NZWG: [
      "http://www.aip.net.nz/pdf/NZWG_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZWG_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZWG_62.1.pdf"
    ],
    NZWU: [
      "http://www.aip.net.nz/pdf/NZWU_31.1.pdf",
      "http://www.aip.net.nz/pdf/NZWU_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZWU_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZWU_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWU_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWU_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZWU_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZWU_61.1_62.1.pdf"
    ],
    NZWR: [
      "http://www.aip.net.nz/pdf/NZWR_44.1_44.2.pdf",
      "http://www.aip.net.nz/pdf/NZWR_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWR_45.3_46.1.pdf",
      "http://www.aip.net.nz/pdf/NZWR_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWR_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZWR_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZWR_62.1_62.2.pdf"
    ],
    NZWP: [
      "http://www.aip.net.nz/pdf/NZWP_31.1_32.1.pdf",
      "http://www.aip.net.nz/pdf/NZWP_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_33.3_33.4.pdf",
      "http://www.aip.net.nz/pdf/NZWP_33.5_41.1.pdf",
      "http://www.aip.net.nz/pdf/NZWP_41.2_41.3.pdf",
      "http://www.aip.net.nz/pdf/NZWP_43.1.pdf",
      "http://www.aip.net.nz/pdf/NZWP_43.2_43.3.pdf",
      "http://www.aip.net.nz/pdf/NZWP_43.4_43.5.pdf",
      "http://www.aip.net.nz/pdf/NZWP_43.6_43.7.pdf",
      "http://www.aip.net.nz/pdf/NZWP_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_45.3_45.4.pdf",
      "http://www.aip.net.nz/pdf/NZWP_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_53.1_53.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_61.1_62.1.pdf",
      "http://www.aip.net.nz/pdf/NZWP_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZWP_62.3_62.4.pdf"
    ],
    NZWT: [
      "http://www.aip.net.nz/pdf/NZWT_33.1.pdf",
      "http://www.aip.net.nz/pdf/NZWT_45.1_45.2.pdf",
      "http://www.aip.net.nz/pdf/NZWT_51.1_52.1.pdf",
      "http://www.aip.net.nz/pdf/NZWT_62.1.pdf"
    ],
    NZWB: [
      "http://www.aip.net.nz/pdf/NZWB_31.1_31.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_31.3.pdf",
      "http://www.aip.net.nz/pdf/NZWB_33.1_33.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_33.3.pdf",
      "http://www.aip.net.nz/pdf/NZWB_34.1_34.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_43.1_43.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_43.3_43.4.pdf",
      "http://www.aip.net.nz/pdf/NZWB_45.1.pdf",
      "http://www.aip.net.nz/pdf/NZWB_51.1_51.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_52.1_52.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_53.1.pdf",
      "http://www.aip.net.nz/pdf/NZWB_61.1.pdf",
      "http://www.aip.net.nz/pdf/NZWB_62.1_62.2.pdf",
      "http://www.aip.net.nz/pdf/NZWB_62.3.pdf",
      "http://www.aip.net.nz/pdf/NZWB_62.4_62.5.pdf",
      "http://www.aip.net.nz/pdf/NZWB_62.6.pdf",
      "http://www.aip.net.nz/pdf/NZWB_62.7_62.8.pdf",
      "http://www.aip.net.nz/pdf/NZWB_63.1_63.2.pdf"
    ]
  }
};
